// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCceOYC7sRQYAqX4e444UCnUPuuf2mmrM0',
    appId: '1:933726014323:web:213e6bd67934bc212f5306',
    messagingSenderId: '933726014323',
    projectId: 'push-notification-web-f812d',
    authDomain: 'push-notification-web-f812d.firebaseapp.com',
    storageBucket: 'push-notification-web-f812d.appspot.com',
    measurementId: 'G-TTFZGLTJ6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfhvnD3ZZoCLF7rXLdZuQKmHR2QDzpAnA',
    appId: '1:933726014323:android:9414e6f599242abc2f5306',
    messagingSenderId: '933726014323',
    projectId: 'push-notification-web-f812d',
    storageBucket: 'push-notification-web-f812d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL2_f7PhcB2XendJSfXEyLuDu1qJNYbrQ',
    appId: '1:933726014323:ios:ef60476b0c0f5a332f5306',
    messagingSenderId: '933726014323',
    projectId: 'push-notification-web-f812d',
    storageBucket: 'push-notification-web-f812d.appspot.com',
    iosBundleId: 'com.example.sampleProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL2_f7PhcB2XendJSfXEyLuDu1qJNYbrQ',
    appId: '1:933726014323:ios:330272990c1bf52f2f5306',
    messagingSenderId: '933726014323',
    projectId: 'push-notification-web-f812d',
    storageBucket: 'push-notification-web-f812d.appspot.com',
    iosBundleId: 'com.example.sampleProject.RunnerTests',
  );
}
